In [1]:
#import numpy
import numpy as np

In [3]:
#create a list
l = [1,2,3,4]

In [5]:
#convert into array
ar = np.array(l)

In [6]:
type(ar)

numpy.ndarray

In [7]:
#convert into 2D array
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [11]:
#convert into array
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a = [2,3,4]

In [10]:
np.asanyarray(a)

array([2, 3, 4])

In [12]:
#convert into matrix
b = np.matrix(a)

In [13]:
b

matrix([[2, 3, 4]])

In [14]:
np.asanyarray(b)

matrix([[2, 3, 4]])

In [15]:
a = np.array(l)

In [17]:
c = a

In [18]:
c

array([1, 2, 3, 4])

In [19]:
a

array([1, 2, 3, 4])

In [21]:
c[0]=100

In [22]:
c

array([100,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [25]:
d = np.copy(a)

In [26]:
d

array([100,   2,   3,   4])

In [27]:
a

array([100,   2,   3,   4])

In [28]:
a[1] = 400

In [29]:
d

array([100,   2,   3,   4])

In [30]:
a

array([100, 400,   3,   4])

In [31]:
np.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
iterable = (i*i for i in range(5))

In [35]:
np.fromiter(iterable , float)

array([ 0.,  1.,  4.,  9., 16.])

In [37]:
np.fromstring('2023 2024', sep = ' ' )

array([2023., 2024.])

In [38]:
np.fromstring('2023 ,2024' , sep = ' ,')

array([2023., 2024.])

In [39]:
#numpy data types

In [40]:
l = [2,3,4,5,6]

In [42]:
ar = np.asanyarray(l)

In [43]:
ar.ndim

1

In [45]:
ar2 = np.array([[1,2,3] , [2,3,4]])

In [46]:
ar2.ndim

2

In [47]:
ar.size

5

In [48]:
ar2.size

6

In [49]:
ar.shape

(5,)

In [50]:
ar2.shape

(2, 3)

In [53]:
ar.dtype

dtype('int32')

In [54]:
ar2.dtype

dtype('int32')

In [55]:
ar3 = np.array([(1.4,45,45) , (23,45,66)])

In [56]:
ar3.dtype

dtype('float64')

In [57]:
ar3

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [59]:
list(range(5))

[0, 1, 2, 3, 4]

In [61]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [62]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [63]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
f = np.zeros((3,4,2))

In [69]:
f.ndim

3

In [70]:
f

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [73]:
 ar4 =np.zeros((3,4,2,6))

In [74]:
ar4.ndim

4

In [75]:
np.ones(4)

array([1., 1., 1., 1.])

In [78]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [80]:
on = np.ones((2,3,2))

In [81]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [82]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [84]:
on - 1

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [88]:
np.empty((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [89]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [90]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [92]:
np.logspace(2,5 , 10 , base =2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [95]:
 data = np.random.randn(3,4)

In [94]:
import pandas as pd 

In [96]:
pd.DataFrame(data)

0         1         2         3
0  0.218045 -1.646722  1.677741 -0.644389
1  0.136446 -0.690949  0.261560 -0.846134
2  0.637056  1.223928  0.742579 -0.961729

In [101]:
 data1 = np.random.rand(3,4)

In [102]:
pd.DataFrame(data1)

0         1         2         3
0  0.413256  0.045727  0.834310  0.001069
1  0.937054  0.763848  0.080609  0.278529
2  0.342677  0.504271  0.002429  0.281245

In [108]:
pd.DataFrame(np.random.randint(1,110 ,(300,400))).to_csv("test.csv")

In [111]:
data2 = data1.reshape(6,2)

In [112]:
data2

array([[0.41325568, 0.04572706],
       [0.83430968, 0.00106923],
       [0.93705412, 0.76384757],
       [0.08060868, 0.27852917],
       [0.3426771 , 0.50427113],
       [0.00242884, 0.28124474]])

In [114]:
data2[1][1]

0.0010692313583423596

In [119]:
data2[2:5,1]

array([0.76384757, 0.27852917, 0.50427113])

In [122]:
arr = np.random.randint(1,100 , (5,5))

In [123]:
arr>50

array([[ True,  True, False,  True, False],
       [ True,  True,  True, False,  True],
       [False,  True, False,  True,  True],
       [ True, False,  True,  True, False],
       [False,  True,  True, False, False]])

In [124]:
arr[arr>50]

array([70, 90, 61, 58, 77, 76, 61, 93, 89, 52, 72, 91, 77, 85, 83])

In [125]:
arr

array([[70, 90, 45, 61,  3],
       [58, 77, 76,  6, 61],
       [16, 93, 17, 89, 52],
       [72, 17, 91, 77, 10],
       [32, 85, 83, 32, 15]])

In [128]:
arr[2:4 , [1,2]]

array([[93, 17],
       [17, 91]])

In [130]:
arr[0][0] = 5000

In [131]:
arr

array([[5000,   90,   45,   61,    3],
       [  58,   77,   76,    6,   61],
       [  16,   93,   17,   89,   52],
       [  72,   17,   91,   77,   10],
       [  32,   85,   83,   32,   15]])

In [132]:
arr1 = np.random.randint(1,3 ,(3,3))
arr2 = np.random.randint(1,3 ,(3,3))

In [133]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [1, 1, 2]])

In [134]:
arr2

array([[1, 2, 2],
       [2, 2, 1],
       [2, 2, 1]])

In [135]:
arr1+arr2

array([[2, 3, 4],
       [4, 3, 3],
       [3, 3, 3]])

In [136]:
arr1-arr2

array([[ 0, -1,  0],
       [ 0, -1,  1],
       [-1, -1,  1]])

In [137]:
arr1*arr2

array([[1, 2, 4],
       [4, 2, 2],
       [2, 2, 2]])

In [139]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [1. , 0.5, 2. ],
       [0.5, 0.5, 2. ]])

In [140]:
arr1@arr2

array([[ 7,  8,  5],
       [ 8, 10,  7],
       [ 7,  8,  5]])

In [141]:
arr1/0

C:\Users\prati\AppData\Local\Temp\ipykernel_20548\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [142]:
arr1**2

array([[1, 1, 4],
       [4, 1, 4],
       [1, 1, 4]], dtype=int32)

In [143]:
#numpy - broadcasting 

In [145]:
arr5 = np.zeros((4,4))

In [146]:
row = np.array([1,2,3,4])

In [147]:
arr5 + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [148]:
row.ndim

1

In [149]:
row.shape

(4,)

In [150]:
row.transpose()

array([1, 2, 3, 4])

In [152]:
col = np.array([[1,2,3,4]])

In [154]:
col.T + arr5

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [155]:
arr

array([[5000,   90,   45,   61,    3],
       [  58,   77,   76,    6,   61],
       [  16,   93,   17,   89,   52],
       [  72,   17,   91,   77,   10],
       [  32,   85,   83,   32,   15]])

In [156]:
np.sqrt(arr)

array([[70.71067812,  9.48683298,  6.70820393,  7.81024968,  1.73205081],
       [ 7.61577311,  8.77496439,  8.71779789,  2.44948974,  7.81024968],
       [ 4.        ,  9.64365076,  4.12310563,  9.43398113,  7.21110255],
       [ 8.48528137,  4.12310563,  9.53939201,  8.77496439,  3.16227766],
       [ 5.65685425,  9.21954446,  9.11043358,  5.65685425,  3.87298335]])

In [157]:
np.exp(arr)

C:\Users\prati\AppData\Local\Temp\ipykernel_20548\3764917082.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(arr)


array([[           inf, 1.22040329e+39, 3.49342711e+19, 3.10429794e+26,
        2.00855369e+01],
       [1.54553894e+25, 2.75851345e+33, 1.01480039e+33, 4.03428793e+02,
        3.10429794e+26],
       [8.88611052e+06, 2.45124554e+40, 2.41549528e+07, 4.48961282e+38,
        3.83100800e+22],
       [1.85867175e+31, 2.41549528e+07, 3.31740010e+39, 2.75851345e+33,
        2.20264658e+04],
       [7.89629602e+13, 8.22301271e+36, 1.11286375e+36, 7.89629602e+13,
        3.26901737e+06]])

In [159]:
np.log2(arr)

array([[12.28771238,  6.4918531 ,  5.4918531 ,  5.93073734,  1.5849625 ],
       [ 5.857981  ,  6.26678654,  6.24792751,  2.5849625 ,  5.93073734],
       [ 4.        ,  6.53915881,  4.08746284,  6.47573343,  5.70043972],
       [ 6.169925  ,  4.08746284,  6.50779464,  6.26678654,  3.32192809],
       [ 5.        ,  6.40939094,  6.37503943,  5.        ,  3.9068906 ]])