In [1]:
#numpy array manipulation 
import numpy as np

In [3]:
arr = np.random.randint(1,10 , (3,4))

In [4]:
arr.reshape(6,2)

array([[9, 8],
       [2, 8],
       [3, 7],
       [6, 4],
       [4, 8],
       [4, 8]])

In [5]:
arr.reshape(2,6)

array([[9, 8, 2, 8, 3, 7],
       [6, 4, 4, 8, 4, 8]])

In [6]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [8]:
arr.reshape(2,-4444)

array([[9, 8, 2, 8, 3, 7],
       [6, 4, 4, 8, 4, 8]])

In [9]:
arr.T

array([[9, 3, 4],
       [8, 7, 8],
       [2, 6, 4],
       [8, 4, 8]])

In [10]:
arr

array([[9, 8, 2, 8],
       [3, 7, 6, 4],
       [4, 8, 4, 8]])

In [11]:
arr.flatten()

array([9, 8, 2, 8, 3, 7, 6, 4, 4, 8, 4, 8])

In [15]:
arr1 = np.array([1,2,3,3,4])

In [16]:
arr1.ndim

1

In [18]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 3, 4]])

In [19]:
arr

array([[9, 8, 2, 8],
       [3, 7, 6, 4],
       [4, 8, 4, 8]])

In [20]:
np.squeeze(arr)

array([[9, 8, 2, 8],
       [3, 7, 6, 4],
       [4, 8, 4, 8]])

In [21]:
data = np.array([[1] , [2] , [3]])

In [22]:
data

array([[1],
       [2],
       [3]])

In [23]:
np.squeeze(data)

array([1, 2, 3])

In [24]:
arr1

array([1, 2, 3, 3, 4])

In [25]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [27]:
np.roll(arr1 ,shift = 2)

array([3, 4, 1, 2, 3])

In [28]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [33]:
arr2 = np.random.randint(1,10 , (3,4))

In [34]:
arr3 = np.random.randint(1,10 , (3,4))

In [35]:
arr2 + arr3

array([[13,  4, 10,  8],
       [ 7,  7,  6,  9],
       [ 7,  6, 12,  4]])

In [36]:
arr2*arr3

array([[40,  3, 16, 12],
       [10,  6,  9, 20],
       [ 6,  8, 27,  3]])

In [37]:
arr2/arr3

array([[1.6       , 3.        , 0.25      , 0.33333333],
       [0.4       , 0.16666667, 1.        , 1.25      ],
       [6.        , 0.5       , 0.33333333, 3.        ]])

In [38]:
arr2-arr3

array([[ 3,  2, -6, -4],
       [-3, -5,  0,  1],
       [ 5, -2, -6,  2]])

In [40]:
arr2%arr3

array([[3, 0, 2, 2],
       [2, 1, 0, 1],
       [0, 2, 3, 0]], dtype=int32)

In [41]:
arr2 ** arr3

array([[32768,     3,   256,    64],
       [   32,     1,    27,   625],
       [    6,    16, 19683,     3]], dtype=int32)

In [42]:
arr2 & arr3

array([[0, 1, 0, 2],
       [0, 0, 3, 4],
       [0, 0, 1, 1]], dtype=int32)

In [43]:
~arr2

array([[-9, -4, -3, -3],
       [-3, -2, -4, -6],
       [-7, -3, -4, -4]], dtype=int32)

In [44]:
arr2 | arr3

array([[13,  3, 10,  6],
       [ 7,  7,  3,  5],
       [ 7,  6, 11,  3]], dtype=int32)

In [45]:
arr2>arr3

array([[ True,  True, False, False],
       [False, False, False,  True],
       [ True, False, False,  True]])

In [46]:
#string function

In [47]:
arr4 = np.array(['sudh','kumar'])

In [50]:
np.char.upper(arr4)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [51]:
np.char.title(arr4)

array(['Sudh', 'Kumar'], dtype='<U5')

In [52]:
np.char.capitalize(arr4)

array(['Sudh', 'Kumar'], dtype='<U5')

In [53]:
#numpy mathmatcal function

In [55]:
arr2

array([[8, 3, 2, 2],
       [2, 1, 3, 5],
       [6, 2, 3, 3]])

In [56]:
np.sin(arr2)

array([[ 0.98935825,  0.14112001,  0.90929743,  0.90929743],
       [ 0.90929743,  0.84147098,  0.14112001, -0.95892427],
       [-0.2794155 ,  0.90929743,  0.14112001,  0.14112001]])

In [57]:
np.cos(arr2)

array([[-0.14550003, -0.9899925 , -0.41614684, -0.41614684],
       [-0.41614684,  0.54030231, -0.9899925 ,  0.28366219],
       [ 0.96017029, -0.41614684, -0.9899925 , -0.9899925 ]])

In [58]:
np.tan(arr2)

array([[-6.79971146, -0.14254654, -2.18503986, -2.18503986],
       [-2.18503986,  1.55740772, -0.14254654, -3.38051501],
       [-0.29100619, -2.18503986, -0.14254654, -0.14254654]])

In [60]:
np.tanh(arr2)

array([[0.99999977, 0.99505475, 0.96402758, 0.96402758],
       [0.96402758, 0.76159416, 0.99505475, 0.9999092 ],
       [0.99998771, 0.96402758, 0.99505475, 0.99505475]])

In [61]:
np.log10(arr2)

array([[0.90308999, 0.47712125, 0.30103   , 0.30103   ],
       [0.30103   , 0.        , 0.47712125, 0.69897   ],
       [0.77815125, 0.30103   , 0.47712125, 0.47712125]])

In [62]:
np.exp(arr2)

array([[2.98095799e+03, 2.00855369e+01, 7.38905610e+00, 7.38905610e+00],
       [7.38905610e+00, 2.71828183e+00, 2.00855369e+01, 1.48413159e+02],
       [4.03428793e+02, 7.38905610e+00, 2.00855369e+01, 2.00855369e+01]])

In [63]:
np.sqrt(arr2)

array([[2.82842712, 1.73205081, 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.73205081, 2.23606798],
       [2.44948974, 1.41421356, 1.73205081, 1.73205081]])

In [65]:
np.power(arr2,2)

array([[64,  9,  4,  4],
       [ 4,  1,  9, 25],
       [36,  4,  9,  9]], dtype=int32)

In [66]:
np.mean(arr2)

3.3333333333333335

In [68]:
np.median(arr2)

3.0

In [69]:
np.std(arr2)

1.9293061504650375

In [70]:
np.var(arr2)

3.722222222222222

In [71]:
np.min(arr2)

1

In [72]:
np.max(arr2)

8