In [1]:
#sort & searching ,counting function....

In [2]:
import numpy as np 

In [4]:
arr = np.array([67,8,78,23,4,53,2,56,79,1])

In [5]:
np.sort(arr)

array([ 1,  2,  4,  8, 23, 53, 56, 67, 78, 79])

In [7]:
np.searchsorted(arr, 45)

2

In [8]:
arr1 = np.array([0,345,456,0.0,0,0.0])

In [9]:
np.count_nonzero(arr1)

2

In [10]:
arr

array([67,  8, 78, 23,  4, 53,  2, 56, 79,  1])

In [13]:
np.where(arr > 6)

(array([0, 1, 2, 3, 5, 7, 8], dtype=int64),)

In [15]:
np.extract(arr>6 , arr)

array([67,  8, 78, 23, 53, 56, 79])

In [16]:
#numpy byte swapping 

In [17]:
arr.byteswap()

array([1124073472,  134217728, 1308622848,  385875968,   67108864,
        889192448,   33554432,  939524096, 1325400064,   16777216])

In [18]:
#numpy copies & views

In [19]:
a = np.copy(arr)

In [20]:
b = arr.view()

In [21]:
b

array([67,  8, 78, 23,  4, 53,  2, 56, 79,  1])

In [22]:
arr

array([67,  8, 78, 23,  4, 53,  2, 56, 79,  1])

In [23]:
#numpy matrix library

In [24]:
import numpy.matlib as nm

In [25]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [26]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [28]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
#numpy linear algebra

In [34]:
arr5 = np.random.randint([[2,3] , [3,4]])
arr6 = np.random.randint([[5,3] , [3,4]])

In [35]:
np.dot(arr5,arr6)

array([[2, 2],
       [2, 2]])

In [36]:
arr5@arr6

array([[2, 2],
       [2, 2]])